language: python
python: "3.7"
# before_install:
#   - sudo apt update
#   - sudo apt install firefox-geckodriver
install: "pip install -r requirements.txt"
# before_script:
#   - sh python ./manage.py runserver
script:
  - SECRET_KEY="whatever" ./manage.py test
  # - python functional_tests.py